#!/usr/bin/python3

"""
Screenguppy: An ASCII fish friend to hang out in your screen session.
(c) 2017 Finn Ellis. Free to use under the MIT license; see LICENSE.
https://github.com/relsqui/screenguppy
"""

import datetime

RFISH="><ε°>"
LFISH="<°3><"
WIDTH=80
SPEED=2

def triangle_wave(x, period):
    y = x % period - period/2
    if y < 0:
        asc = False
    else:
        asc = True
    return int(abs(y)), asc

def fish(forward):
    if forward:
        return RFISH
    else:
        return LFISH

def pad(count):
    return " " * count

def width():
    return WIDTH - len(RFISH) - 2

lspaces, forward = triangle_wave(int(datetime.datetime.now().timestamp() * SPEED), width())
rspaces = width() - lspaces
print(pad(lspaces) + fish(forward) + pad(rspaces))
