#!/usr/bin/python3

"""
Screenguppy: An ASCII fish friend to hang out in your screen session.
(c) 2017 Finn Ellis. Free to use under the MIT license; see LICENSE.
https://github.com/relsqui/screenguppy
"""

import datetime
import sys

RFISH="><ε°>"
LFISH="<°3><"
WIDTH=76 - len(RFISH)
SPEED=2

def triangle_wave(x, period):
    y = x % period - period/2
    if y < 0:
        asc = False
    else:
        asc = True
    return int(abs(y)), asc

def fish(forward):
    if forward:
        return RFISH
    else:
        return LFISH

def pad(count):
    return " " * count

if len(sys.argv) > 1:
    WIDTH=int(sys.argv[1])

spaces, forward = triangle_wave(int(datetime.datetime.now().timestamp() * SPEED), WIDTH * 2)
print(pad(spaces) + fish(forward) + pad(WIDTH - spaces))
